(() => {
'use strict';
const $=id=>document.getElementById(id), config=window.SEC_YEARBOOK_CONFIG||{}, reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const personalLeft=$('left-page').innerHTML,personalRight=$('right-page').innerHTML;
let phase='cover',busy=false,sound=false,audio,record=null,imageBlob=null,preview=false,entries=[],spread=0,spreadCount=1,toastTimer,portraitURL=null,revealed=false;
const wait=ms=>new Promise(r=>setTimeout(r,reduced?10:ms));
function notice(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').classList.add('visible');toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),6000)}
function state(next){phase=next;document.body.dataset.phase=next;for(const id of ['cover','loading','ready','result','yearbook','error'])$(id+'-actions').hidden=id!==next;}
function lock(value){busy=value;for(const id of ['mine','class','meet','connect','demo','retry'])$(id).disabled=value;}
function paper(){if(!sound||reduced)return;try{audio||=new(window.AudioContext||window.webkitAudioContext)();void audio.resume();const t=audio.currentTime,n=audio.createBufferSource(),g=audio.createGain(),f=audio.createBiquadFilter(),b=audio.createBuffer(1,audio.sampleRate*.48,audio.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1);n.buffer=b;f.type='lowpass';f.frequency.setValueAtTime(600,t);f.frequency.linearRampToValueAtTime(1900,t+.18);f.frequency.linearRampToValueAtTime(500,t+.48);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.026,t+.14);g.gain.exponentialRampToValueAtTime(.0001,t+.47);n.connect(f);f.connect(g);g.connect(audio.destination);n.start();n.onended=()=>{n.disconnect();f.disconnect();g.disconnect()}}catch{}}
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(sound));};
function safeURL(value){const u=new URL(value,location.href);if(!['https:','http:'].includes(u.protocol))throw Error('Invalid image');return u.href}
async function api(path,options={}){if(!config.apiBase)throw Error('Service unavailable');const r=await fetch(config.apiBase+path,{credentials:'include',...options,headers:{'Content-Type':'application/json',...options.headers},signal:AbortSignal.timeout(90000)});if(!r.ok)throw Error('Request failed');return r.json()}
async function openBook(){if($('book').classList.contains('open'))return;$('book').classList.add('open');await wait(1650);$('book').classList.add('settled');}
function pageCopy(page){const copy=page.cloneNode(true);copy.removeAttribute('id');copy.querySelectorAll('[id]').forEach(node=>{node.dataset.sourceId=node.id;node.removeAttribute('id')});copy.className='page-copy';copy.inert=true;copy.setAttribute('aria-hidden','true');return copy;}
async function turn(backward=false,label='',mutate){
 if(reduced){if(mutate)await mutate();return;}
 const oldLeft=pageCopy($('left-page')),oldRight=pageCopy($('right-page'));
 const sheet=document.createElement('div'),front=document.createElement('div'),back=document.createElement('div'),hold=document.createElement('div');
 sheet.className='sheet'+(backward?' backward':'');front.className='sheet-face';back.className='sheet-face sheet-back';
 try{
  if(mutate)await mutate();
  const newLeft=pageCopy($('left-page')),newRight=pageCopy($('right-page'));
  front.append(backward?newRight:oldRight);back.append(backward?oldLeft:newLeft);
  if(label&&!mutate){front.replaceChildren();const word=document.createElement('span');word.className='turn-caption';word.textContent=label;front.append(word);}
  hold.className='page-hold '+(backward?'hold-right':'hold-left');hold.append(backward?oldRight:oldLeft);
  sheet.append(front,back);$('sheets').append(hold,sheet);paper();
  await Promise.all(sheet.getAnimations().map(animation=>animation.finished.catch(()=>{})));
 }finally{sheet.remove();hold.remove();}
}
function restorePersonal(){if($('portrait'))return;$('left-page').innerHTML=personalLeft;$('right-page').innerHTML=personalRight;wireSmile();if(portraitURL){$('portrait').src=portraitURL;$('portrait').alt=`Yearbook portrait of @${record.handle}`;$('portrait').hidden=!revealed;$('empty').hidden=revealed;$('smile').hidden=false;$('frame-copy').hidden=true;$('handle').textContent='@'+record.handle;$('quote').textContent='“'+record.quote+'”';}}
async function setPortrait(item){record={handle:String(item.handle||'').replace(/^@/,''),quote:String(item.quote||''),portraitUrl:safeURL(item.portraitUrl),id:item.id};if(!record.handle)throw Error('Missing profile');const r=await fetch(record.portraitUrl,{signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('Image unavailable');imageBlob=await r.blob();if(!imageBlob.type.startsWith('image/'))throw Error('Invalid image');if(portraitURL)URL.revokeObjectURL(portraitURL);const url=URL.createObjectURL(imageBlob);portraitURL=url;$('portrait').dataset.objectUrl=url;$('portrait').src=url;await $('portrait').decode();$('portrait').alt=`Yearbook portrait of @${record.handle}. ${record.quote}`;$('handle').textContent='@'+record.handle;$('quote').textContent='“'+record.quote+'”';}
async function generate(){const job=await api('/portraits',{method:'POST',body:JSON.stringify({edition:'september-2026'})});if(job.portraitUrl)return job;if(!job.id)throw Error('Missing job');for(let i=0;i<90;i++){await new Promise(r=>setTimeout(r,2000));const result=await api('/portraits/'+encodeURIComponent(job.id));if(result.status==='failed')throw Error('Generation failed');if(result.status==='complete')return result;}throw Error('Generation timed out')}
async function start(isPreview){if(busy)return;lock(true);preview=isPreview;revealed=false;restorePersonal();$('portrait').hidden=true;$('empty').hidden=false;$('smile').hidden=true;$('frame-copy').hidden=false;state('loading');$('loading-copy').textContent=preview?'Exploring picture day…':'Creating your yearbook portrait…';$('loading-label').textContent=preview?'PREVIEW · EXAMPLE PORTRAIT':'X CONNECTED · PICTURE DAY';$('progress').style.width='12%';let outcome=(preview?Promise.resolve(config.sample):generate()).then(setPortrait).then(()=>null,e=>e);try{await openBook();for(const [i,line]of ['The class that builds.','See you in the halls.','Your page.'].entries()){$('progress').style.width=(30+i*20)+'%';await turn(false,line)}const error=await outcome;if(error)throw error;$('progress').style.width='100%';$('smile').hidden=false;$('frame-copy').hidden=true;state('ready');$('smile').focus({preventScroll:true})}catch{$('error-copy').textContent='Your portrait couldn’t be created. Please try again.';state('error')}finally{lock(false)}}
function shutter(){if(!sound)return;try{audio||=new(window.AudioContext||window.webkitAudioContext)();void audio.resume();const t=audio.currentTime;for(const [delay,volume]of [[0,.05],[.065,.025]]){const n=audio.createBufferSource(),g=audio.createGain(),f=audio.createBiquadFilter(),buffer=audio.createBuffer(1,Math.floor(audio.sampleRate*.04),audio.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);n.buffer=buffer;f.type='highpass';f.frequency.value=1600;g.gain.value=volume;n.connect(f);f.connect(g);g.connect(audio.destination);n.start(t+delay);n.onended=()=>{n.disconnect();f.disconnect();g.disconnect()};}}catch{}}
function wireSmile(){$('smile').onclick=async()=>{
 if(phase!=='ready'||busy)return;lock(true);$('smile').disabled=true;
 try{shutter();const flash=$('camera-flash');const animation=reduced?null:flash.animate([{opacity:0},{opacity:.94,offset:.12},{opacity:0}],{duration:480,easing:'ease-out'});
 await wait(65);revealed=true;$('empty').hidden=true;$('portrait').hidden=false;state('result');
 $('result-label').textContent=preview?'PREVIEW · EXAMPLE PORTRAIT':'OFFICIALLY IN THE YEARBOOK';$('share-note').textContent=preview?'Preview: saves the example image and opens X. Attach it before posting.':'Your portrait will be attached to your post. You choose when to share.';
 if(animation)await animation.finished.catch(()=>{});$('share').focus({preventScroll:true});
 }finally{lock(false)}
}}

wireSmile();
function connect(){if(config.authUrl){location.assign(safeURL(config.authUrl));return;}$('connection-dialog').showModal()}
$('connect').onclick=connect;$('demo').onclick=()=>start(true);$('dialog-demo').onclick=()=>{$('connection-dialog').close();start(true)};$('close-dialog').onclick=()=>$('connection-dialog').close();$('retry').onclick=()=>start(preview);
function download(){if(!imageBlob)return;const u=URL.createObjectURL(imageBlob),a=document.createElement('a');a.href=u;a.download=`solana-high-${record.handle}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(u),5000)}
$('download').onclick=download;
$('share').onclick=async()=>{if(!record)return;const text=`Class of ’26. ${record.quote}. #SolanaHigh`;if(preview){window.open('https://x.com/intent/post?text='+encodeURIComponent(text),'_blank','noopener,noreferrer');download();notice('Example portrait saved. Attach it in the X composer before posting.');return;}$('share').disabled=true;try{const result=await api('/portraits/'+encodeURIComponent(record.id)+'/share',{method:'POST',body:JSON.stringify({text})});if(!result.postUrl)throw Error('Missing post');notice('Your portrait was posted on X.');$('share-note').textContent='Shared on X. See you in the halls.';}catch{notice('Your post couldn’t be shared. Your portrait is safe—please try again.')}finally{$('share').disabled=false}};
function card(item){const figure=document.createElement('figure');figure.className='class-card';if(item){const img=document.createElement('img');img.src=safeURL(item.portraitUrl);img.alt=`Yearbook portrait of @${item.handle}`;img.loading='lazy';const caption=document.createElement('figcaption');caption.textContent='@'+String(item.handle).replace(/^@/,'');figure.append(img,caption)}else{const vacancy=document.createElement('div');vacancy.className='vacant';vacancy.textContent='Your classmate';const caption=document.createElement('figcaption');caption.textContent='A story still to come.';figure.append(vacancy,caption)}return figure}
function renderSpread(){for(let side=0;side<2;side++){const page=$(side?'right-page':'left-page');page.replaceChildren();const content=document.createElement('div');content.className='class-page';const heading=document.createElement('div');heading.className='class-heading';heading.textContent=side?'THE PEOPLE WHO MAKE IT':'SOLANA HIGH · CLASS OF ’26';const grid=document.createElement('div');grid.className='class-grid';for(let i=0;i<4;i++)grid.append(card(entries[spread*8+side*4+i]));const foot=document.createElement('div');foot.className='folio';const label=document.createElement('span');label.textContent=config.apiBase?'SOLANA HIGH':'PREVIEW · OPEN PLACES';const number=document.createElement('span');number.textContent=String(spread*2+side+1).padStart(3,'0');foot.append(label,number);content.append(heading,grid,foot);page.append(content)}$('pages').textContent=`${spread*2+1} — ${spread*2+2} / ${spreadCount*2}`;$('prev').disabled=spread===0;$('next').disabled=spread>=spreadCount-1;}
async function showClass(){if(busy)return;lock(true);state('loading');$('loading-copy').textContent='Opening the class yearbook…';$('loading-label').textContent='THE CLASS OF ’26';$('progress').style.width='50%';try{if(config.apiBase){const data=await api('/yearbook?edition=september-2026');if(!Array.isArray(data.entries))throw Error('Invalid yearbook');entries=data.entries;spreadCount=Math.max(1,Math.ceil(entries.length/8));}else{entries=[config.sample];spreadCount=2;}spread=0;await openBook();await turn(false,'Meet the class.',renderSpread);state('yearbook');$('class-label').textContent=config.apiBase?`${entries.length} CLASSMATE${entries.length===1?'':'S'} · CLASS OF ’26`:'PREVIEW · ONE EXAMPLE PORTRAIT';$('class-note').textContent=config.apiBase?(entries.length?'Four people per page. Every completed portrait joins the class.':'The first page is waiting for its first classmate.'):'Example portrait + open places. Real classmates appear after generation.';$('mine').removeAttribute('aria-current');$('class').setAttribute('aria-current','page')}catch{state('error');$('error-copy').textContent='The yearbook couldn’t load. Please open The yearbook to try again.'}finally{lock(false)}}
async function navigate(direction){if(phase!=='yearbook'||busy||spread+direction<0||spread+direction>=spreadCount)return;lock(true);$('prev').disabled=$('next').disabled=true;try{await turn(direction<0,'',()=>{spread+=direction;renderSpread()})}finally{lock(false);$('prev').disabled=spread===0;$('next').disabled=spread>=spreadCount-1;}}
$('prev').onclick=()=>navigate(-1);$('next').onclick=()=>navigate(1);$('class').onclick=$('meet').onclick=showClass;
$('mine').onclick=async()=>{if(busy)return;lock(true);try{if(record){await turn(true,'',restorePersonal);state(revealed?'result':'ready');$('share-note').textContent=preview?'Preview: saves the example image and opens X. Attach it before posting.':'Your portrait will be attached to your post.'}else{$('book').classList.remove('settled');void $('cover').offsetWidth;$('book').classList.add('closing');$('book').classList.remove('open');await wait(1650);$('book').classList.remove('closing');restorePersonal();state('cover')}$('class').removeAttribute('aria-current');$('mine').setAttribute('aria-current','page')}catch{notice('Your portrait couldn’t load. Please try again.')}finally{lock(false)}};
let touchX=null;$('stage').addEventListener('touchstart',e=>{touchX=e.touches[0].clientX},{passive:true});$('stage').addEventListener('touchend',e=>{if(phase==='yearbook'&&touchX!==null){const dx=e.changedTouches[0].clientX-touchX;if(Math.abs(dx)>55)navigate(dx<0?1:-1)}touchX=null},{passive:true});document.addEventListener('keydown',e=>{if(phase==='yearbook'&&!busy&&!['INPUT','TEXTAREA'].includes(e.target.tagName)){if(e.key==='ArrowRight')navigate(1);if(e.key==='ArrowLeft')navigate(-1)}});
state('cover');if(config.apiBase){$('preview-label').hidden=true;$('demo').hidden=true;api('/session').then(session=>{if(session.connected)start(false)}).catch(()=>notice('Couldn’t check your X connection. Please try again.'))}
})();
